---
- name: School Bell Install
  hosts: all 
  become: yes

  tasks:
    - name: Upgrade existing packages
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 3600

    - name: Install Python School Bell package in venv
      shell: |
        source {{ ansible_env.HOME }}/.local/bin/activate
        pip install git+https://github.com/psmsmets/school-bell.git

    # Create service and enable without link!

    - name: Just force systemd to reread configs
      ansible.builtin.systemd_service:
        daemon_reload: true

    - name: Restart School Bell
      service:
        name: school-bell
        state: restarted
        enable: yes

