---
- name: School Bell Update
  hosts: pibell-aso-vtilokalen, pibell-aso-intercom, pibell-bs-kleuter, pibell-bs-lager
  become: yes

tasks:
  - name: Upgrade existing packages
    ansible.builtin.apt:
      upgrade: yes
      update_cache: yes
      cache_valid_time: 3600

  - name: Update Python School Bell package in venv
    ansible.builtin.pip:
      name: git+https://github.com/psmsmets/school-bell.git
      virtualenv: "{{ ansible_env.HOME }}/.local"
      virtualenv_python: python3
      state: latest
      extra_args: "--upgrade"

  - name: Just force systemd to reread configs
    ansible.builtin.systemd_service:
      daemon_reload: true

  - name: Restart School Bell
    ansible.builtin.service:
      name: school-bell
      state: restarted
      enabled: yes
